### ISSUE TITLE
Update failed for ActionGroup: Rerun

### ISSUE THREAD

**Issue by Netsrfr** [beansoftapp/react-native-console#21]
Issue occurs with both [Rerun 'iOS Run Simulator'], [Rerun 'debug Android'], and when launching WebStorm.

WebStorm 2017.3.2
Began with React Native Console 1.1.0
Upgraded to 1.1.2 without resolution

```
update failed for ActionGroup: Rerun (Rerun)[Rerun 'iOS Run Simulator']: Can't find resource for bundle java.util.PropertyResourceBundle, key dumb.aware.run.configurations
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key dumb.aware.run.configurations
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:171)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:162)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:142)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:66)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:56)
	at com.github.beansoftapp.reatnative.idea.views.RNConsoleImpl$RerunAction.isDumbAware(RNConsoleImpl.java:55)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:125)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:257)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:1005)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:182)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:643)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.n(FocusManagerImpl.java:624)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.f(FocusManagerImpl.java:594)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:476)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1396)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1380)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by beansoftapp** [comment]
Thanks for your bug report, I've run to this issue sometimes, and it's fixed now. I've tested that and it works.

https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar, you can download it now for a test. If no problem, a new fix will be upload to the plugin center.
