### ISSUE TITLE
supporting switch between yarn and npm

### ISSUE THREAD

**Issue by colarzy** [beansoftapp/react-native-console#46]
Please add a setting to choose between yarn and npm to run the project.
When clicking on run-android, I get this error:

/usr/local/bin/yarn react-native run-android
Internal Error: app@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at t.RunInstallPleaseResolver.getCandidates (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:863677)
    at t.MultiResolver.getCandidates (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:41320)
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:36:581640
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:36:857805
    at new Promise (<anonymous>)
    at e.exports (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:857787)
    at i (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:91764)
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:24:91837
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:24:91880
    at new Promise (<anonymous>)

Process finished with exit code 1

**Comment by beansoftapp** [comment]
Hello, I'd like to know which version React Native you are using?

**Comment by colarzy** [comment]
0.62.2

**Comment by beansoftapp** [comment]
i've fixed it in https://github.com/beansoftapp/react-native-console/blob/master/react-native-console_release.jar, will soon be approved by Jetbrains plugin center.
