### ISSUE TITLE
Plugin failing when IDE Starts

### ISSUE THREAD

**Issue by FernandoAvanzo** [beansoftapp/react-native-console#84]
## What happened

the plugin was failing when the IDE starts

## Version information

IntelliJ IDEA `2024.2` • React Native Console plugin `com.github.beansoftapp.reatnative.idea 2023.2.1`
## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.beansoftapp.reatnative.idea.actions.RevealFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.beansoftapp.reatnative.idea]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by beansoft** [comment]
The plugin version 2024.2 has been released; please update it and see if it helps.
